### ISSUE TITLE
启动atxweb后连接设备时报错

### ISSUE THREAD

**Issue by cherishGuo123** [NetEaseGame/ATX#129]
# Version information
```
- ATX Version: 1.1.3.dev3
- Python Version: 2.7.8

$ python -m atxweb
2017-05-17 09:28:58.560 INFO  [webide: 413] Server started.
2017-05-17 09:28:58.575 INFO  [webide: 414] Listening port on 127.0.0.1:10010
WARNING:tornado.access:404 GET /$%7Bimg.path%7D (127.0.0.1) 3.00ms
2017-05-17 09:28:59.259 INFO  [webide: 119] WebSocket connected
android device list: [u'3e413efd']
2017-05-17 09:28:59.870 INFO  [webide: 119] WebSocket connected
android device list: [u'3e413efd']
2017-05-17 09:29:02.883 INFO  [webide: 217] WebSocket closed
ERROR:tornado.application:Uncaught exception POST /device (127.0.0.1)
HTTPServerRequest(protocol='http', host='127.0.0.1:10010', method='POST', uri='/device', version='HT
TP/1.1', remote_ip='127.0.0.1', headers={'Origin': 'http://127.0.0.1:10010', 'Content-Length': '7',
'Accept-Language': 'zh-CN,zh;q=0.8', 'Accept-Encoding': 'gzip, deflate', 'Host': '127.0.0.1:10010',
'Accept': 'application/json, text/javascript, */*; q=0.01', 'User-Agent': 'Mozilla/5.0 (Windows NT 6
.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.75 Safari/537.36 LBBROWSER', 'Con
nection': 'keep-alive', 'X-Requested-With': 'XMLHttpRequest', 'Referer': 'http://127.0.0.1:10010/',
'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8'})
Traceback (most recent call last):
  File "c:\Python27\lib\site-packages\tornado\web.py", line 1509, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "c:\Python27\lib\site-packages\atxweb\server.py", line 343, in post
    device = atx.connect(**settings)
  File "c:\Python27\lib\site-packages\atx\__init__.py", line 77, in connect
    c = cls(connect_url, **kwargs)
TypeError: __init__() got multiple values for keyword argument 'serialno'
ERROR:tornado.access:500 POST /device (127.0.0.1) 129.00ms
```

**Comment by ghost62184** [comment]
我也遇到了同样的问题

**Comment by clobob** [comment]
也碰到同样问题

**Comment by caivivi** [comment]
我也碰到同样的问题，osx 10.12.5， xcode：8.3.3， iphone 5s：10.3.2，python：2.7.10，麻烦能看一下，谢谢啦！

**Comment by holysor** [comment]
我也碰到这样的问题 ，mac上经常连不上

**Comment by codeskyblue** [comment]
根据最新的README安装文档，再安装一次试试

**Comment by codeskyblue** [comment]
atxwebide已废弃
