### ISSUE TITLE
个别功能不兼容android8.0

### ISSUE THREAD

**Issue by Jack-Tian** [NetEaseGame/ATX#143]
current_app()不兼容android8.0，希望可以支持。
android8.0预览版：https://developer.android.com/preview/download.html

**Comment by codeskyblue** [comment]
你哪来的这么高版本的手机

**Comment by Jack-Tian** [comment]
增加一个8.0不兼容问题：
机型：展讯芯片平台工程机
d.screenshot()无法截图。
报错信息：
2017-08-15 13:54:04.670 WARN  [atx.drivers.mixin: 390] warning, screenshot failed [2/1], retry again
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\IPython\core\interactiveshell.py", line 2881, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-40-6a206739f9dc>", line 1, in <module>
    d.screenshot()
  File "C:\Python27\lib\site-packages\atx\drivers\mixin.py", line 62, in _inner
    _retval = fn(*args, **kwargs)
  File "C:\Python27\lib\site-packages\atx\drivers\mixin.py", line 391, in screenshot
    screen = self._take_screenshot()
  File "C:\Python27\lib\site-packages\atx\drivers\android.py", line 274, in _take_screenshot
    screen = self._screenshot_uiauto()
  File "C:\Python27\lib\site-packages\atx\drivers\android.py", line 254, in _screenshot_uiauto
    raise IOError("Screenshot use uiautomator failed.")
IOError: Screenshot use uiautomator failed.


解题思路：
当前screenshot方法目前尝试了minicap和uiauto 2种方法。
希望再增加adb的screencap的方式的尝试（例如atx.adbkit.device.Device中的_adb_screencap()）。
前两种都不管用时，可以用screencap的方式截图。

**Comment by Jack-Tian** [comment]
@codeskyblue 用google原生机（nexus6p, nexus5x等）可以刷8.0预览版。
过不了多久8.0正式版就会出来了。

**Comment by codeskyblue** [comment]
8.1之后的目前可以用minicap截图了
