### ISSUE TITLE
ChromeDriver Error

### ISSUE THREAD

**Issue by henrymark92** [NetEaseGame/ATX#145]
Code:
[import atx
from atx.ext.chromedriver import ChromeDriver

d = atx.connect()
driver = ChromeDriver(d).driver()](url)
```
Error:
[2.993][INFO]: received WebDriver request: POST /session {
   "capabilities": {
      "alwaysMatch": {
         "chromeOptions": {
            "androidActivity": ".MainActivity",
            "androidDeviceSerial": "emulator-5554",
            "androidPackage": "com.android.chrome",
            "androidProcess": "com.android.chrome",
            "androidUseRunningApp": true
         }
      },
      "firstMatch": [  ]
   },
   "desiredCapabilities": {
      "chromeOptions": {
         "androidActivity": ".MainActivity",
         "androidDeviceSerial": "emulator-5554",
         "androidPackage": "com.android.chrome",
         "androidProcess": "com.android.chrome",
         "androidUseRunningApp": true
      }
   }
}
[2.997][INFO]: sending WebDriver response: 200 {
   "sessionId": "",
   "status": 13,
   "value": {
      "message": "unknown error: Adb command \"host:transport:0015emulator-5554|shell:pm path com.android.chrome\" failed, is the Adb server running?\n  (Driver info: chromedriver=2.0,platform=Windows NT 6.1 SP1 x..."
   }
}
Traceback (most recent call last):
  File "D:/source/auto_testl/Test.py", line 5, in <module>
    driver = ChromeDriver(d).driver()
  File "D:\source\auto_testl\atx\ext\chromedriver.py", line 64, in driver
    dr = webdriver.Remote('http://localhost:%d' % self._port, capabilities)
  File "C:\python32\python-2.7.10\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 98, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "C:\python32\python-2.7.10\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 188, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\python32\python-2.7.10\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 256, in execute
    self.error_handler.check_response(response)
  File "C:\python32\python-2.7.10\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Adb command "host:transport:0015emulator-5554|shell:pm path com.android.chrome" failed, is the Adb server running?
  (Driver info: chromedriver=2.0,platform=Windows NT 6.1 SP1 x86_64)
```

**Comment by codeskyblue** [comment]
看提示呀
