### ISSUE TITLE
pyton -m atx gui时报“uiautomator.JsonRPCError: JsonRPC Error code: -32001”

### ISSUE THREAD

**Issue by hongjojjay** [NetEaseGame/ATX#147]
python版本3.5.4，ATX version 1.1.3 dev35

执行python -m atx gui，然后报错，100%重现

```
2017-10-26 10:23:28.792 DEBUG [tkgui: 413] gui starting(scale: 0.5) ...
Traceback (most recent call last):
  File "d:\program files\python\python35\Lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\program files\python\python35\Lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\hongjojjay\venv\lib\site-packages\atx\__main__.py", line 171, in <module>
    main()
  File "C:\Users\hongjojjay\venv\lib\site-packages\atx\__main__.py", line 168, in main
    args.func(args)
  File "C:\Users\hongjojjay\venv\lib\site-packages\atx\__main__.py", line 48, in _inner
    return inject(mod.main, pargs)
  File "C:\Users\hongjojjay\venv\lib\site-packages\atx\__main__.py", line 39, in inject
    return func(*args)
  File "C:\Users\hongjojjay\venv\lib\site-packages\atx\cmds\tkgui.py", line 426, in main
    gui = CropIDE('ATX GUI SN: %s' % serial, ratio=scale, device=d)
  File "C:\Users\hongjojjay\venv\lib\site-packages\atx\cmds\tkgui.py", line 99, in __init__
    self._init_vars()
  File "C:\Users\hongjojjay\venv\lib\site-packages\atx\cmds\tkgui.py", line 160, in _init_vars
    self.draw_image(self._device.screenshot())
  File "C:\Users\hongjojjay\venv\lib\site-packages\atx\drivers\mixin.py", line 63, in _inner
    _retval = fn(*args, **kwargs)
  File "C:\Users\hongjojjay\venv\lib\site-packages\atx\drivers\mixin.py", line 405, in screenshot
    screen = self._take_screenshot()
  File "C:\Users\hongjojjay\venv\lib\site-packages\atx\drivers\android.py", line 304, in _take_screenshot
    screen = self._screenshot_minicap()
  File "C:\Users\hongjojjay\venv\lib\site-packages\atx\drivers\android.py", line 257, in _screenshot_minicap
    self._minicap_params(), phone_tmp_file)
  File "C:\Users\hongjojjay\venv\lib\site-packages\atx\drivers\android.py", line 241, in _minicap_params
    rotation = self.rotation
  File "C:\Users\hongjojjay\venv\lib\site-packages\atx\drivers\android.py", line 228, in rotation
    return self.adb_device.rotation() or self.info['displayRotation']
  File "C:\Users\hongjojjay\venv\lib\site-packages\atx\drivers\android.py", line 110, in info
    return self._uiauto.info
  File "C:\Users\hongjojjay\venv\lib\site-packages\uiautomator\__init__.py", line 615, in info
    return self.server.jsonrpc.deviceInfo()
  File "C:\Users\hongjojjay\venv\lib\site-packages\uiautomator\__init__.py", line 417, in wrapper
    return _method_obj(*args, **kwargs)
  File "C:\Users\hongjojjay\venv\lib\site-packages\uiautomator\__init__.py", line 196, in __call__
    return self.remote_call(data)
  File "C:\Users\hongjojjay\venv\lib\site-packages\uiautomator\__init__.py", line 183, in remote_call
    "%s: %s" % (exception_type, error["message"])
uiautomator.JsonRPCError: JsonRPC Error code: -32001, Message: java.lang.IllegalStateException: UiAutomation not connected!
```

**Comment by deanarcher** [comment]
I have the same problem.

**Comment by lxf920125** [comment]
我也遇到过 有时是异常中断导致，有时是adb版本太低导致

**Comment by codeskyblue** [comment]
再升级下atx试试

**Comment by codeskyblue** [comment]
换成了uiautomator2作为底层，这个问题应该没有了
