### ISSUE TITLE
IOError: uiautomator start failed: INSTRUMENTATION_STATUS: id=ActivityManagerService

### ISSUE THREAD

**Issue by wumingzhao** [NetEaseGame/ATX#152]
## Version information
- ATX Version: 1.1.3.dev36
- Python Version: Python 2.7.9

## What steps will reproduce the problem?
windows环境
adb用的是1.0.39
链接端口
使用的是网易MUMU模拟器
按照官网介绍的快速开发只写了:

> import atx
> d = atx.connect() 
> d.screenshot('screen.png') 

就弹出故障了

## Do you have any log or screenshots?
log:
2017-12-03 01:56:32.455 WARN  [atx.drivers.mixin: 408] warning, screenshot faile
d [2/1], retry again
Traceback (most recent call last):
  File "playgame.py", line 5, in <module>
    d.screenshot('screen.png')
  File "C:\Python27\lib\site-packages\atx\drivers\mixin.py", line 63, in _inner
    _retval = fn(*args, **kwargs)
  File "C:\Python27\lib\site-packages\atx\drivers\mixin.py", line 409, in screen
shot
    screen = self._take_screenshot()
  File "C:\Python27\lib\site-packages\atx\drivers\android.py", line 307, in _tak
e_screenshot
    screen = self._screenshot_uiauto()
  File "C:\Python27\lib\site-packages\atx\drivers\android.py", line 275, in _scr
eenshot_uiauto
    self._uiauto.screenshot(tmp_file)
  File "C:\Python27\lib\site-packages\uiautomator\__init__.py", line 667, in scr
eenshot
    self.info # try to launch uiautomator server
  File "C:\Python27\lib\site-packages\uiautomator\__init__.py", line 626, in inf
o
    return self.server.jsonrpc.deviceInfo()
  File "C:\Python27\lib\site-packages\uiautomator\__init__.py", line 428, in wra
pper
    server.start(timeout=30)
  File "C:\Python27\lib\site-packages\uiautomator\__init__.py", line 509, in sta
rt
    raise IOError("uiautomator start failed: " + str(stdout))
IOError: uiautomator start failed: INSTRUMENTATION_STATUS: id=ActivityManagerSer
vice
INSTRUMENTATION_STATUS: Error=Unable to find instrumentation info for: Component
Info{com.github.uiautomator.test/android.support.test.runner.AndroidJUnitRunner}

INSTRUMENTATION_STATUS_CODE: -1
android.util.AndroidException: INSTRUMENTATION_FAILED: com.github.uiautomator.te
st/android.support.test.runner.AndroidJUnitRunner
        at com.android.commands.am.Am.runInstrument(Am.java:865)
        at com.android.commands.am.Am.onRun(Am.java:282)
        at com.android.internal.os.BaseCommand.run(BaseCommand.java:47)
        at com.android.commands.am.Am.main(Am.java:76)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:243)
        at dalvik.system.NativeStart.main(Native Method)

可以帮忙看看吗？谢谢！

**Comment by codeskyblue** [comment]
好像是有个apk没装上去

**Comment by wumingzhao** [comment]
apk? 是指安装环境的apk还是游戏的apk?

**Comment by wumingzhao** [comment]
是指com.github.uiautomator这个apk吗？

**Comment by codeskyblue** [comment]
你先用这个项目，看看还会报错不 https://github.com/openatx/uiautomator2
