### ISSUE TITLE
android python -m atx gui出现JsonRPC Error code: 504错误

### ISSUE THREAD

**Issue by chargogd** [NetEaseGame/ATX#153]
## Version information
- ATX Version: 1.1.3.dev36
- Python Version: 2.7.10

链接华为P8的安卓手机时，提示以下错误。请问要怎么解决？
排查过程：
1、已开启usb开发者模式（文件传输方式），命令行adb devices可以获取到序列号
2、辅助功能里也开启了ATX助手服务
3、使用automator viewer可以获取到控件

(venv) ➜  ATX git:(master) ✗ python -m atx gui
2017-12-14 21:02:22.531 DEBUG [tkgui: 404] gui starting(scale: 0.5) ...
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/chargo/svn/ATX/atx/__main__.py", line 171, in <module>
    main()
  File "/Users/chargo/svn/ATX/atx/__main__.py", line 168, in main
    args.func(args)
  File "/Users/chargo/svn/ATX/atx/__main__.py", line 48, in _inner
    return inject(mod.main, pargs)
  File "/Users/chargo/svn/ATX/atx/__main__.py", line 39, in inject
    return func(*args)
  File "atx/cmds/tkgui.py", line 417, in main
    gui = CropIDE('ATX GUI SN: %s' % serial, ratio=scale, device=d)
  File "atx/cmds/tkgui.py", line 90, in __init__
    self._init_vars()
  File "atx/cmds/tkgui.py", line 151, in _init_vars
    self.draw_image(self._device.screenshot())
  File "atx/drivers/mixin.py", line 63, in _inner
    _retval = fn(*args, **kwargs)
  File "atx/drivers/mixin.py", line 405, in screenshot
    screen = self._take_screenshot()
  File "atx/drivers/android.py", line 304, in _take_screenshot
    screen = self._screenshot_minicap()
  File "atx/drivers/android.py", line 257, in _screenshot_minicap
    self._minicap_params(), phone_tmp_file)
  File "atx/drivers/android.py", line 241, in _minicap_params
    rotation = self.rotation
  File "atx/drivers/android.py", line 228, in rotation
    return self.adb_device.rotation() or self.info['displayRotation']
  File "atx/drivers/android.py", line 110, in info
    return self._uiauto.info
  File "/Users/chargo/svn/ATX/venv/lib/python2.7/site-packages/uiautomator/__init__.py", line 626, in info
    return self.server.jsonrpc.deviceInfo()
  File "/Users/chargo/svn/ATX/venv/lib/python2.7/site-packages/uiautomator/__init__.py", line 423, in wrapper
    return _method_obj(*args, **kwargs)
  File "/Users/chargo/svn/ATX/venv/lib/python2.7/site-packages/uiautomator/__init__.py", line 196, in __call__
    return self.remote_call(data)
  File "/Users/chargo/svn/ATX/venv/lib/python2.7/site-packages/uiautomator/__init__.py", line 176, in remote_call
    raise JsonRPCError(res.status_code, "HTTP Return code is not 200")
uiautomator.JsonRPCError: JsonRPC Error code: 504, Message: HTTP Return code is not 200

**Comment by chenabc1** [comment]
问题解决了吗？

**Comment by codeskyblue** [comment]
更新一下，应该好了
