### ISSUE TITLE
关于截图工具的问题

### ISSUE THREAD

**Issue by xu269610644** [NetEaseGame/ATX#154]
您好我在主页中看到，ATX支持的环境为：Python >= 2.7 && <= 3.5，我现在的环境为：

> (ATX) C:\Users\Administrator>python
Python 3.5.4 (v3.5.4:3f56838, Aug  8 2017, 02:17:05) [MSC v.1900 64 bit (AMD64)]
 on win32
Type "help", "copyright", "credits" or "license" for more information.

但是在执行：
> (ATX) C:\Users\Administrator>python -m atx gui

时提示我：

> Traceback (most recent call last):
  File "c:\users\administrator\appdata\local\programs\python\python35\Lib\runpy.
py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\administrator\appdata\local\programs\python\python35\Lib\runpy.
py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Python\Evns\ATX\lib\site-packages\atx\__main__.py", line 171, in <mod
ule>
    main()
  File "D:\Python\Evns\ATX\lib\site-packages\atx\__main__.py", line 168, in main

    args.func(args)
  File "D:\Python\Evns\ATX\lib\site-packages\atx\__main__.py", line 45, in _inne
r
    __import__(module_path)
  File "D:\Python\Evns\ATX\lib\site-packages\atx\cmds\tkgui.py", line 20, in <mo
dule>
    import Tkinter as tk
ImportError: No module named 'Tkinter'

这是由于python2.7+和3.5+包的命名不一致所导致的，那么应该如何处理呢？

**Comment by codeskyblue** [comment]
去官网重新下载个python，重新安装就好了，我上次就是这样弄好的

**Comment by codeskyblue** [comment]
已修复
