### ISSUE TITLE
使用minicap录屏报错，貌似是说缺少cv

### ISSUE THREAD

**Issue by bsshanghai** [NetEaseGame/ATX#158]
atx 1.1.2版本
opencv_contrib_python装好了
cv2我看到python libs下面也有
图贴不上来，粘log吧。
然后执行过程
C:\Users\Administrator>python -m atx screenrecord -o D:\pycharm\out.avi
starting minicap 1080x1920@1080x1920/90
minicap connected (1, 24, 4995, 1080, 1920, 1080, 1920, 1, 2)
Traceback (most recent call last):
  File "D:\Python27-64bit\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "D:\Python27-64bit\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "D:\Python27-64bit\lib\site-packages\atx\__main__.py", line 171, in <modu
le>
    main()
  File "D:\Python27-64bit\lib\site-packages\atx\__main__.py", line 168, in main
    args.func(args)
  File "D:\Python27-64bit\lib\site-packages\atx\__main__.py", line 48, in _inner

    return inject(mod.main, pargs)
  File "D:\Python27-64bit\lib\site-packages\atx\__main__.py", line 39, in inject

    return func(*args)
  File "D:\Python27-64bit\lib\site-packages\atx\cmds\screenrecord.py", line 51,
in main
    fourcc = cv2.cv.FOURCC(*'MJPG')
**AttributeError: 'module' object has no attribute 'cv'**

看最后报错是说没有cv的模块吗？也不是很确定，所以就来问一下可以去哪里安装么？当然自己也在搜索。

**Comment by codeskyblue** [comment]
安装一下opencv就好了

**Comment by bsshanghai** [comment]
先去这里，https://github.com/NetEaseGame/ATX/commit/f4d861992839b7cf8027d9d0af8286645505b213
用命令安装了pip install opencv_python
然后尝试启动手机同步屏幕
这次不报cv出错了.谢谢
