### ISSUE TITLE
atx.connect()一直都连不上，安卓手机是OPPO A37m 看adb devices是处于devices状态的呀，我看直接用uiautomator2去连就可以，奇怪了，用的是python2.7.14

### ISSUE THREAD

**Issue by GitDzreal93** [NetEaseGame/ATX#172]
```
Traceback (most recent call last):
  File "E:/project/python/atx_demo/atx_demo.py", line 15, in <module>
    d = atx.connect()
  File "C:\Python27\lib\site-packages\atx\__init__.py", line 83, in connect
    c = cls(connect_url, **kwargs)
  File "C:\Python27\lib\site-packages\atx\drivers\android.py", line 94, in __init__
    if not self._uiauto.alive:
  File "C:\Python27\lib\site-packages\uiautomator2\__init__.py", line 383, in alive
    r = self._reqsess.get(self.path2url('/ping'), timeout=2)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 521, in get
    return self.request('GET', url, **kwargs)
  File "C:\Python27\lib\site-packages\uiautomator2\__init__.py", line 210, in request
    resp = super(TimeoutRequestsSession, self).request(method, url, **kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python27\lib\site-packages\requests\adapters.py", line 490, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', error(10054, ''))
```

**Comment by codeskyblue** [comment]
需要先init才行
