### ISSUE TITLE
 测试报告不支持python3吗？

### ISSUE THREAD

**Issue by gengjikun** [NetEaseGame/ATX#174]
```
import atx
from atx.ext.report import Report

d = atx.connect('http://localhost:8100', platform='ios')
d.start_app('com.netease.cloudmusic')
rp = Report(d)
rp.patch_wda()

d(text=u'网易邮箱').click()
d(xpath=u"//TextField").set_text("jikunshishen@163.com\n")
d(xpath=u"//SecureTextField").set_text("abc321kaixin")
d(text=u'登录').click()
d(text=u'帐 号').click()
d(text=u'退出登录').scroll().click()
d(text=u'确定').click()
d.stop_app()
`

报错如下：

Traceback (most recent call last):
  File "/Users/gengjikun/PycharmProjects/wx_ios_ATX/wxapp_ios/wxtest.py", line 9, in <module>
    d(text=u'网易邮箱').click()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/atx/ext/report/__init__.py", line 119, in _click
    orig_click = pt.get_original(wda.Selector, 'click')
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/atx/ext/report/patch.py", line 59, in get_original
    return _get_original(mod_name, [item_name])[0]
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/atx/ext/report/patch.py", line 45, in _get_original
    module = __import__(name)
TypeError: __import__() argument 1 must be str, not type
```

**Comment by codeskyblue** [comment]
虽然知道有问题，但是没精力去修复了。不过还有别的办法
ATX底层使用的[uiautomator2](https://github.com/openatx/uiautomator2)，测试报告可以用底层库自带的 [SimpleHTMLReport](https://github.com/openatx/uiautomator2/tree/master/uiautomator2/ext/htmlreport)
