### ISSUE TITLE
python2.7 解析apk失败

### ISSUE THREAD

**Issue by xiachunle** [NetEaseGame/ATX#175]
## Version information
- ATX Version: 1.2.1.dev2
- Python Version: 2.7.10

通过 python  -m atx  apkparse  解析包获取失败

错误输出如下:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Library/Python/2.7/site-packages/atx/__main__.py", line 171, in <module>
    main()
  File "/Library/Python/2.7/site-packages/atx/__main__.py", line 168, in main
    args.func(args)
  File "/Library/Python/2.7/site-packages/atx/__main__.py", line 54, in _apk_parse
    manifest = apkparse.parse_apk(args.filename)
  File "/Library/Python/2.7/site-packages/atx/androaxml/__init__.py", line 69, in parse_apk
    return Manifest(AXMLPrinter(manifest).getBuff())
  File "/Library/Python/2.7/site-packages/axmlparserpy/axmlprinter.py", line 52, in __init__
    self.buff += "%s%s=\"%s\"\n" % (self.getPrefix(self.axml.getAttributePrefix(i)), self.axml.getAttributeName(i), self.getAttributeValue(i))
  File "/Library/Python/2.7/site-packages/axmlparserpy/axmlprinter.py", line 80, in getAttributeValue
    return saxutils.escape(self.axml.getAttributeValue(index), entities={'"': '&quot;'})
  File "/Library/Python/2.7/site-packages/axmlparserpy/axmlparser.py", line 254, in getAttributeValue
    return self.sb.getRaw(valueString)
  File "/Library/Python/2.7/site-packages/axmlparserpy/stringblock.py", line 89, in getRaw
    data += chr(self.getShort(self.m_strings, offset))
ValueError: chr() arg not in range(256)

**Comment by codeskyblue** [comment]
考虑到python2快退出舞台了，apkparse在python2中不做支持了，不过在python3中还是可用的

**Comment by jiacy** [comment]
我之前也有遇到这个问题，是依赖包版本的问题，在chr()执行中参数不在256范围内，抛出异常
解决办法：
安装依赖时不要 pip install AxmlParserPY==0.03 这部分代码会导致异常；改用pip install AxmlParserPY 安装0.1的版本     
不会有此问题了

原因分析：
0.03版本依赖，这部分代码会抛出异常
对应代码/site-packages/axmlparserpy/stringblock.py", line 89,
data += chr(self.getShort(self.m_strings, offset))
---------
0.1版本实现如下：
# Unicode character
            data += unichr(self.getShort(self.m_strings, offset))
不会抛出异常，可以正常使用

**Comment by codeskyblue** [comment]
多谢关注，不过现在这个库维护频率变很低了，正在将这个项目中的代码逐渐转移到https://github.com/openatx 下
