### ISSUE TITLE
ATX-GUI和脚本冲突

### ISSUE THREAD

**Issue by bsshanghai** [NetEaseGame/ATX#186]
## Version information
- ATX Version: 1.5.1
- Python Version: 2.7

## What steps will reproduce the problem?
首先开启python -m atx gui
成功连接手机后，进行点击，操作，刷新操作，一切正常。
然后在pycharm里面执行脚本
d = atx.connect()
然后再去gui界面点击并run。报错

2018-06-13 15:05:55.263 DEBUG [tkgui: 293] mouse position: (260.0, 274.0)
Exception in Tkinter callback
Traceback (most recent call last):
  File "D:\Python27-64bit\lib\lib-tk\Tkinter.py", line 1542, in __call__
    return self.func(*args)
  File "D:\Python27-64bit\lib\site-packages\atx\cmds\tkgui.py", line 256, in _ru
n_code
    exec(code)
  File "<string>", line 1, in <module>
  File "D:\Python27-64bit\lib\site-packages\atx\drivers\mixin.py", line 197, in
click
    return self.do_tap(x, y)
  File "D:\Python27-64bit\lib\site-packages\atx\drivers\android.py", line 226, i
n do_tap
    return self._uiauto.click(x, y)
  File "D:\Python27-64bit\lib\site-packages\uiautomator2\__init__.py", line 1183
, in click
    ret = self.jsonrpc.click(x, y)
  File "D:\Python27-64bit\lib\site-packages\uiautomator2\__init__.py", line 349,
 in __call__
    params, http_timeout)
  File "D:\Python27-64bit\lib\site-packages\uiautomator2\__init__.py", line 356,
 in jsonrpc_retry_call
    return self.jsonrpc_call(*args, **kwargs)
  File "D:\Python27-64bit\lib\site-packages\uiautomator2\__init__.py", line 390,
 in jsonrpc_call
    data=data)
  File "D:\Python27-64bit\lib\site-packages\requests\sessions.py", line 555, in
post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "D:\Python27-64bit\lib\site-packages\uiautomator2\__init__.py", line 223,
 in request
    "atx-agent is not running. Fix it with following steps.\n1. Plugin device in
to computer.\n2. Run command \"python -m uiautomator2 init\""
EnvironmentError: atx-agent is not running. Fix it with following steps.
1. Plugin device into computer.
2. Run command "python -m uiautomator2 init"
-----显然手机是连着的，然后atx-agent也是开着的。

然后点击刷新，报错：
WARNING:retry.api:HTTPConnectionPool(host='127.0.0.1', port=10902): Max retries
exceeded with url: /screenshot/0 (Caused by NewConnectionError('<urllib3.connect
ion.HTTPConnection object at 0x0000000009CB42B0>: Failed to establish a new conn
ection: [Errno 10061] ',)), retrying in 0.6 seconds...
WARNING:retry.api:HTTPConnectionPool(host='127.0.0.1', port=10902): Max retries
exceeded with url: /screenshot/0 (Caused by NewConnectionError('<urllib3.connect
ion.HTTPConnection object at 0x0000000009CB41D0>: Failed to establish a new conn
ection: [Errno 10061] ',)), retrying in 0.7 seconds...
WARNING:retry.api:HTTPConnectionPool(host='127.0.0.1', port=10902): Max retries
exceeded with url: /screenshot/0 (Caused by NewConnectionError('<urllib3.connect
ion.HTTPConnection object at 0x0000000009CB4278>: Failed to establish a new conn
ection: [Errno 10061] ',)), retrying in 0.8 seconds...
HTTPConnectionPool(host='127.0.0.1', port=10902): Max retries exceeded with url:
 /screenshot/0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection
 object at 0x0000000009CB40B8>: Failed to establish a new connection: [Errno 100
61] ',))
一顿重试之后未有成功也就挂了。

难道我在pycharm里获取过连接后，GUI那边的就断了？而且还不能重试成功？

回退到1.1.1。就没有两方冲突的情况。

**Comment by codeskyblue** [comment]
有可能是adb 重新启动了的感觉

**Comment by bsshanghai** [comment]
而且atx自带的report也不能用。
在一个脚本里面同时用atx连接，然后使用Report，这样写的话，它最终不运行，提示要init。然而init了也木有用。

ph_serial='FBD4T17817002443'

d=atx.connect(ph_serial)

rppath="F:\\d2\\report\\"
rpnum=len(os.listdir(rppath))
rp_id=rppath+'rp'+str(rpnum+1)

rp = report.Report(d, save_dir=rp_id)
rp.patch_uiautomator()
rp.info("Start test")
尴尬啊
