### ISSUE TITLE
Mac执行python -m atx gui 报错

### ISSUE THREAD

**Issue by Cheese-Yu** [NetEaseGame/ATX#199]
## Version information
- ATX Version: You can get from `python -matx version` 1.2.1.dev8
- Python Version: You can get from `python -V` 2.7.15

## What steps will reproduce the problem?
python -m atx gui
## Do you have any log or screenshots?
(venv) ACA80085:~ cheeseyu$ python -m atx gui
2018-12-29 10:44:47.356 DEBUG [tkgui: 412] gui starting(scale: 0.5) ...
/Users/cheeseyu/venv/lib/python2.7/site-packages/uiautomator2/__init__.py:275: RuntimeWarning: backend atx-agent is not alive, start again ...
  RuntimeWarning)
Traceback (most recent call last):
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/cheeseyu/venv/lib/python2.7/site-packages/atx/__main__.py", line 199, in <module>
    main()
  File "/Users/cheeseyu/venv/lib/python2.7/site-packages/atx/__main__.py", line 195, in main
    args.func(args)
  File "/Users/cheeseyu/venv/lib/python2.7/site-packages/atx/__main__.py", line 49, in _inner
    return inject(mod.main, pargs)
  File "/Users/cheeseyu/venv/lib/python2.7/site-packages/atx/__main__.py", line 40, in inject
    return func(*args)
  File "/Users/cheeseyu/venv/lib/python2.7/site-packages/atx/cmds/tkgui.py", line 420, in main
    d = atx.connect(serial)
  File "/Users/cheeseyu/venv/lib/python2.7/site-packages/atx/__init__.py", line 83, in connect
    c = cls(connect_url, **kwargs)
  File "/Users/cheeseyu/venv/lib/python2.7/site-packages/atx/drivers/android.py", line 93, in __init__
    self._uiauto = uiautomator2.connect_usb(serial)
  File "/Users/cheeseyu/venv/lib/python2.7/site-packages/uiautomator2/__init__.py", line 277, in connect_usb
    "shell", "/data/local/tmp/atx-agent", "server", "-d")
  File "/Users/cheeseyu/venv/lib/python2.7/site-packages/uiautomator2/adbutils.py", line 60, in execute
    'utf-8', errors='ignore'))
EnvironmentError: [Errno subprocess] /usr/local/bin/adb -s d86e281e shell /data/local/tmp/atx-agent server -d: u'/system/bin/sh: /data/local/tmp/atx-agent: not found\n'

请问该如何解决，谢谢。

**Comment by Cheese-Yu** [comment]
Sorry，原来是没有执行`python -m uiautomator2 init`这一步。打扰了~
